# basic options
title: RReganJr Software Developer
author: Ron Regan
# email: rreganjr@acm.org
description: musings
github_username:  rreganjr

# Build settings
markdown: kramdown
theme: minima

# Google Analytics
google_analytics: G-27HZ5SRFK8

#gems:
#  - jekyll-last-modified-at